version: '2.0'
services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: movies
        ports:
            - 27017:27017
    app:
        command: node dist/index.js
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3100:3100
        volumes:
            - .:/app/
        environment:
            JWT_SECRET: ${JWT_SECRET}
            APP_SECRET: secret 
            MONGO_IP: mongo 
            MONGO_PORT: 27017 
            MONGO_DB_NAME: movies
